name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions from Jira 🚀
on:
  repository_dispatch:
    types: [test_jira_automation]

jobs:
  run_if_failure:
    if: ${{ !github.event.client_payload.passed }}
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.prurl }}
        run: echo $MESSAGE
