name: Merge PR

on:
  repository_dispatch:
    types: [test_jira_automation]

env:
  prNo: ${{ github.event.client_payload.prNo }}
  repoUrl: ${{ github.event.client_payload.repoUrl }}

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.prNo;
            console.log('prNumber:', prNumber.split('#')[1].split(']')[0], typeof prNumber, prNumber.length);
            const repoUrl = process.env.repoUrl;
            console.log('repoUrl:', repoUrl, typeof repoUrl, repoUrl.length);
