name: Merge PR

on:
  repository_dispatch:
    types: [test_jira_automation]

env:
  prNo: ${{ github.event.client_payload.prNo }}
  repoUrl: ${{ github.event.client_payload.repoUrl }}

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = process.env.prNo;
            console.log('prNumber:', prNumber.split('#')[1].split(']')[0], typeof prNumber, prNumber.length);
            const repoUrl = process.env.repoUrl;
            console.log('repoUrl:', repoUrl.split(',')[0].split('/')[0].split('[')[1], typeof repoUrl, repoUrl.length);
            const prNo = prNumber.split('#')[1].split(']')[0];
            const owner = repoUrl.split(',')[0].split('/')[0].split('[')[1];
            const repo = repoUrl.split(',')[0].split('/')[1].split(']')[0];
            console.log(prNo, owner, repo);
            const { data: pullRequest } = await github.pulls.get({
              owner: owner,
              repo: repo,
              pull_number: prNo
            });
            
            await github.pulls.merge({
              owner: owner,
              repo: repo,
              pull_number: prNo
            });
