name: Merge Pull Request

on:
  repository_dispatch:
    types: [test_jira_automation]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo, number } = context.issue;

            const { data: pullRequest } = await github.pulls.get({
              owner,
              repo,
              pull_number: 11
            });

            await github.pulls.merge({
              owner,
              repo,
              pull_number: number,
              merge_method: 'merge'
            });
