name: Merge Pull Request

on:
  repository_dispatch:
    types: [test_jira_automation]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge Pull Request
        uses: repo-sync/pull-request-merge@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pull_request_number: #11
